[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci --ignore-scripts'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NEXT_TELEMETRY_DISABLED = '1'

[staticAssets]
# Enable Railway to serve static assets properly
"public" = "./public"
".next/static" = "./.next/static"